MyBookStore.MvcApp/Controllers/BooksController.cs
#nullable disable
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyBookStore.MvcApp.Models;
using MyBookStore.MvcApp.Models.DTO;
using MyBookStore.MvcApp.Models.EF;

namespace MyBookStore.MvcApp.Controllers;

/// <summary>
/// CRUD операции над таблицей "Книги".
/// </summary>
[Authorize(Roles = "Admin")]
public class BooksController : Controller
{
    private readonly BookStoreContext _context;
    private readonly IMapper _mapper;

    public BooksController(BookStoreContext context, IMapper mapper)
    {
        _context = context;
        _mapper = mapper;
    }

    /// <summary>
    /// Таблица.
    /// </summary>
    /// <returns></returns>
    public async Task<IActionResult> Index()
    {
        var bookStoreContext = _context
            .Books
            .Include(b => b.Manufacturer)
            .Include(x => x.Authors)
            .Include(x => x.Genres);
        return View(await bookStoreContext.ToListAsync());
    }

    /// <summary>
    /// Подробная информация о книге.
    /// </summary>
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var book = await _context.Books
            .Include(b => b.Manufacturer)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (book == null)
        {
            return NotFound();
        }

        return View(book);
    }

    /// <summary>
    /// Форма создания книги.
    /// </summary>
    public IActionResult Create()
    {
        ViewData["ManufacturerId"] = new SelectList(_context.Manufacturers, "Id", "Name");
        ViewData["Authors"] = new MultiSelectList(_context.Authors, "Id", "");
        ViewData["Genres"] = new MultiSelectList(_context.Genres, "Id", "Name");
        ViewData["Types"] = new MultiSelectList(_context.BookTypes, "Id", "Name");
        return View();
    }

    /// <summary>
    /// Создать книгу.
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(
        [Bind("Id," +
              "Title," +
              "AuthorIds," +
              "GenreIds," +
              "TypeIds," +
              "ImagePath," +
              "ReceiptDate," +
              "BookTypeId,Price," +
              "Description," +
              "ManufacturerId," +
              "IsOnSale," +
              "Discount")]
        BookDTO bookDto)
    {
        if (ModelState.IsValid)
        {
            var authors = new List<Author>();
            var types = new List<BookType>();
            var genres = new List<Genre>();

            foreach (var authorId in bookDto.AuthorIds)
            {
                authors.Add(await _context
                    .Authors
                    .FirstOrDefaultAsync(x => x.Id == authorId));
            }

            foreach (var typeId in bookDto.TypeIds)
            {
                types.Add(await _context
                    .BookTypes
                    .FirstOrDefaultAsync(x => x.Id == typeId));
            }

            foreach (var genreId in bookDto.GenreIds)
            {
                genres.Add(await _context
                    .Genres
                    .FirstOrDefaultAsync(x => x.Id == genreId));
            }

            var book = _mapper.Map<Book>(bookDto);
            ;
            book.Types = types;
            book.Authors = authors;
            book.Genres = genres;

            _context.Add((object) book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        ViewData["ManufacturerId"] = new SelectList(_context.Manufacturers, "Id", "Name");
        ViewData["Authors"] = new MultiSelectList(_context.Authors, "Id", "");
        ViewData["Genres"] = new MultiSelectList(_context.Genres, "Id", "Name");
        ViewData["Types"] = new MultiSelectList(_context.BookTypes, "Id", "Name");

        return View(bookDto);
    }

    /// <summary>
    /// Форма редактирования книги.
    /// </summary>
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var book = await _context
            .Books
            .Include(x => x.Authors)
            .Include(x => x.Types)
            .Include(x => x.Genres)
            .FirstOrDefaultAsync(x => x.Id == id);

        var bookDto = _mapper.Map<BookDTO>(book);

        bookDto.TypeIds = book.Types.Select(x => x.Id).ToList();
        bookDto.AuthorIds = book.Authors.Select(x => x.Id).ToList();
        bookDto.GenreIds = book.Genres.Select(x => x.Id).ToList();

        if (bookDto == null)
        {
            return NotFound();
        }

        ViewData["ManufacturerId"] = new SelectList(_context.Manufacturers, "Id", "Name", bookDto.ManufacturerId);
        ViewData["Authors"] = new MultiSelectList(_context.Authors, "Id", "", bookDto.AuthorIds);
        ViewData["Genres"] = new MultiSelectList(_context.Genres, "Id", "Name", bookDto.GenreIds);
        ViewData["Types"] = new MultiSelectList(_context.BookTypes, "Id", "Name", bookDto.TypeIds);

        return View(bookDto);
    }

    /// <summary>
    /// Редактировать книгу.
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(
        int id,
        [Bind("Id," +
              "Title," +
              "AuthorIds," +
              "GenreIds," +
              "TypeIds," +
              "ImagePath," +
              "ReceiptDate," +
              "BookTypeId,Price," +
              "Description," +
              "ManufacturerId," +
              "IsOnSale," +
              "Discount")]
        BookDTO bookDto)
    {
        if (id != bookDto.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                var authors = new List<Author>();
                var types = new List<BookType>();
                var genres = new List<Genre>();

                foreach (var authorId in bookDto.AuthorIds)
                {
                    authors.Add(await _context
                        .Authors
                        .FirstOrDefaultAsync(x => x.Id == authorId));
                }

                foreach (var typeId in bookDto.TypeIds)
                {
                    types.Add(await _context
                        .BookTypes
                        .FirstOrDefaultAsync(x => x.Id == typeId));
                }

                foreach (var genreId in bookDto.GenreIds)
                {
                    genres.Add(await _context
                        .Genres
                        .FirstOrDefaultAsync(x => x.Id == genreId));
                }

                var book = await _context
                    .Books
                    .Include(x => x.Authors)
                    .Include(x => x.Types)
                    .Include(x => x.Genres)
                    .FirstOrDefaultAsync(x => x.Id == bookDto.Id);

                _mapper.Map(bookDto, book);
                book.Types = types;
                book.Authors = authors;
                book.Genres = genres;

                _context.Update(book);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BookExists(bookDto.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction(nameof(Index));
        }

        ViewData["ManufacturerId"] = new SelectList(_context.Manufacturers, "Id", "Name", bookDto.ManufacturerId);
        ViewData["Authors"] = new MultiSelectList(_context.Authors, "Id", "", bookDto.AuthorIds);
        ViewData["Genres"] = new MultiSelectList(_context.Genres, "Id", "Name", bookDto.GenreIds);
        ViewData["Types"] = new MultiSelectList(_context.BookTypes, "Id", "Name", bookDto.TypeIds);

        return View(bookDto);
    }

    /// <summary>
    /// Форма удаления книги.
    /// </summary>
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var book = await _context.Books
            .Include(b => b.Manufacturer)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (book == null)
        {
            return NotFound();
        }

        return View(book);
    }

    /// <summary>
    /// Удалить книгу.
    /// </summary>
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var book = await _context.Books.FindAsync(id);
        _context.Books.Remove(book);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool BookExists(int id)
    {
        return _context.Books.Any(e => e.Id == id);
    }
}

MyBookStore.MvcApp/Controllers/OrdersController.cs
#nullable disable
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyBookStore.MvcApp.Models;
using MyBookStore.MvcApp.Models.EF;

namespace MyBookStore.MvcApp.Controllers;

[Authorize]
public class OrdersController : Controller
{
    private readonly BookStoreContext _context;

    /// <summary>
    /// Корзина.
    /// </summary>
    private readonly Cart _cart;

    public OrdersController(BookStoreContext context, Cart cart)
    {
        _context = context;
        _cart = cart;
    }

    /// <summary>
    /// Список заказов.
    /// </summary>
    /// <returns></returns>
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Index()
    {
        var bookStoreContext =
            _context
                .Orders
                .Include(o => o.DeliveryType)
                .Include(o => o.Status);
        return View(await bookStoreContext.ToListAsync());
    }

    /// <summary>
    /// Форма создания заказа.
    /// </summary>
    public IActionResult Create()
    {
        ViewData["DeliveryTypeId"] = new SelectList(_context.DeliveryTypes, "Id", "Name");
        ViewData["StatusId"] = new SelectList(_context.OrderStatuses, "Id", "Name");
        return View(new Order());
    }

    /// <summary>
    /// Создать заказ.
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Order order)
    {
        if (_cart.Lines.Count == 0)
        {
            ModelState.AddModelError("", "Корзина пуста");
        }

        ModelState.Remove("CartLines");
        ModelState.Remove("Status");
        ModelState.Remove("DeliveryType");

        if (ModelState.IsValid)
        {
            order.CartLines = _cart.Lines;
            order.Status = _context
                .OrderStatuses
                .First(x => x.Name == "Создан");
            order.CreatedAt = DateTime.Now;

            _context.AttachRange(order.CartLines.Select(x => x.Book));

            if (order.Id == 0)
            {
                _context.Add(order);
            }


            await _context.SaveChangesAsync();
            return RedirectToAction("List", "BookStore");
        }

        ViewData["DeliveryTypeId"] = new SelectList(_context.DeliveryTypes, "Id", "Name", order.DeliveryTypeId);
        return View(order);
    }

    /// <summary>
    /// Форма редактирования заказа.
    /// </summary>
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var order = await _context.Orders.FindAsync(id);
        if (order == null)
        {
            return NotFound();
        }

        ViewData["DeliveryTypeId"] = new SelectList(_context.DeliveryTypes, "Id", "Name", order.DeliveryTypeId);
        ViewData["StatusId"] = new SelectList(_context.OrderStatuses, "Id", "Name", order.StatusId);
        return View(order);
    }

    /// <summary>
    /// Редактировать заказ.
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Edit(int id,
        [Bind("Id,Name,Middlename,Surname,StatusId,DeliveryTypeId,Address,CreatedAt")]
        Order order)
    {
        if (id != order.Id)
        {
            return NotFound();
        }

        ModelState.Remove("CartLines");
        ModelState.Remove("Status");
        ModelState.Remove("DeliveryType");

        if (ModelState.IsValid)
        {
            try
            {
                order.Status = _context.OrderStatuses.First(x => x.Id == order.StatusId);
                order.DeliveryType = _context.DeliveryTypes.First(x => x.Id == order.DeliveryTypeId);
                order.CreatedAt = _context.Orders.AsNoTracking().First(x => x.Id == order.Id).CreatedAt;

                _context.Update(order);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OrderExists(order.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction(nameof(Index));
        }

        ViewData["DeliveryTypeId"] = new SelectList(_context.DeliveryTypes, "Id", "Name", order.DeliveryTypeId);
        ViewData["StatusId"] = new SelectList(_context.OrderStatuses, "Id", "Name", order.StatusId);
        return View(order);
    }

    /// <summary>
    /// Форма удаления заказа.
    /// </summary>
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var order = await _context.Orders
            .Include(o => o.DeliveryType)
            .Include(o => o.Status)
            .Include(o => o.CartLines)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (order == null)
        {
            return NotFound();
        }

        return View(order);
    }

    /// <summary>
    /// Удалить заказ.
    /// </summary>
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var order = await _context
            .Orders
            .Include(o => o.DeliveryType)
            .Include(o => o.Status)
            .Include(o => o.CartLines)
            .FirstOrDefaultAsync(o => o.Id == id);
        _context.Orders.Remove(order);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool OrderExists(int id)
    {
        return _context.Orders.Any(e => e.Id == id);
    }
}

MyBookStore.MvcApp/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MyBookStore.MvcApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/comments.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/commentForm.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/rating.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/MyBookStore.MvcApp.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="BookStore" asp-action="List">
                <span><i class="bi bi-book"></i> Мой книжный</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="BookStore" asp-action="List">Каталог</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="BookStore" asp-action="Privacy">О нас</a>
                    </li>

                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Администрирование
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Books" asp-action="Index">Книги</a>
                                <a class="dropdown-item" asp-controller="Authors" asp-action="Index">Авторы</a>
                                <a class="dropdown-item" asp-controller="BookTypes" asp-action="Index">Типы издания</a>
                                <a class="dropdown-item" asp-controller="Genres" asp-action="Index">Жанры</a>
                                <a class="dropdown-item" asp-controller="Manufacturers" asp-action="Index">Издатели</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">Заказы</a>
                            </div>
                        </li>
                    }
                    @if (!SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Register">Регистрация</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Вход</a>
                        </li>
                    }
                </ul>
                @if (SignInManager.IsSignedIn(User))
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <ul class="nav navbar-nav ml-5">
                                <li class="dropdown">
                                    <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span>
                                            <i class="bi bi-person"></i>
                                        </span>
                                        <strong>@User.Identity.Name</strong>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <a class="dropdown-item"
                                           asp-controller="Account"
                                           asp-action="Profile"
                                           asp-route-id="@User.FindFirstValue(ClaimTypes.NameIdentifier)">
                                            Личный кабинет
                                        </a>
                                        <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Выход</a>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                }

            </div>
        </div>
    </nav>
    @* <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel"> *@
    @*     <ol class="carousel-indicators"> *@
    @*         <li data-target="#carouselExampleIndicators" data-slide-to="0"></li> *@
    @*         <li data-target="#carouselExampleIndicators" data-slide-to="1" class="active"></li> *@
    @*         <li data-target="#carouselExampleIndicators" data-slide-to="2"></li> *@
    @*     </ol> *@
    @*     <div class="carousel-inner"> *@
    @*         <div class="carousel-item"> *@
    @*             <img class="d-block w-100" src="..." alt="First slide"> *@
    @*         </div> *@
    @*         <div class="carousel-item active"> *@
    @*             <img class="d-block w-100" src="https://ianrhr.unl.edu/image/library-banner.png" alt="Second slide"> *@
    @*         </div> *@
    @*         <div class="carousel-item"> *@
    @*             <img class="d-block w-100" src="..." alt="Third slide"> *@
    @*         </div> *@
    @*     </div> *@
    @*     <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev"> *@
    @*         <span class="carousel-control-prev-icon" aria-hidden="true"></span> *@
    @*         <span class="sr-only">Previous</span> *@
    @*     </a> *@
    @*     <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next"> *@
    @*         <span class="carousel-control-next-icon" aria-hidden="true"></span> *@
    @*         <span class="sr-only">Next</span> *@
    @*     </a> *@
    @* </div> *@
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - MyBookStore.MvcApp - <a asp-area="" asp-controller="BookStore" asp-action="Privacy">Privacy</a>
    </div>
</footer>
@* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
@* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>