MyBookStore.MvcApp/Models/Cart.cs
namespace MyBookStore.MvcApp.Models;

/// <summary>
/// Корзина.
/// </summary>
public class Cart
{
    public List<CartLine> Lines { get; set; } = new();

    public decimal TotalValue => Lines.Sum(x => x.Book.Price * x.Quantity);

    public virtual void AddItem(Book book, int quantity)
    {
        var line = Lines.FirstOrDefault(x => x.Book.Id == book.Id);

        if (line == null)
        {
            Lines.Add(new CartLine
            {
                Book = book,
                Quantity = quantity
            });
        }
        else
        {
            line.Quantity += quantity;
        }
    }

    public virtual void RemoveLine(Book book) => Lines.RemoveAll(l => l.Book.Id == book.Id);

    public virtual void Clear() => Lines.Clear();
}

MyBookStore.MvcApp/Models/CartLine.cs
namespace MyBookStore.MvcApp.Models;

/// <summary>
/// Позиция в корзине.
/// </summary>
public class CartLine
{
    public int Id { get; set; }
    public Book Book { get; set; }
    public int Quantity { get; set; }

    public decimal Total => Book.Price * Quantity;
}

MyBookStore.MvcApp/Controllers/BookStoreController.cs
using System.Diagnostics;
using Korzh.EasyQuery.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using MyBookStore.MvcApp.Models;
using MyBookStore.MvcApp.Models.EF;
using MyBookStore.MvcApp.Models.ViewModels;

namespace MyBookStore.MvcApp.Controllers;

/// <summary>
/// Каталог книжного магазина.
/// </summary>
[Authorize]
public class BookStoreController : Controller
{
    private readonly ILogger<BookStoreController> _logger;
    private readonly BookStoreContext _context;

    public BookStoreController(ILogger<BookStoreController> logger, BookStoreContext context)
    {
        _logger = logger;
        _context = context;
    }

    /// <summary>
    /// Каталог книг.
    /// </summary>
    /// <param name="searchText">Запрос полнотекстового поиска.</param>
    /// <param name="pageNumber">Номер страницы.</param>
    /// <param name="pageSize">Размер страницы.</param>
    /// <param name="manufacturerId">Фильтрация по издателю.</param>
    /// <param name="sortOrder">Порядок сортировки.</param>
    /// <param name="sortBy">Поле сортировки.</param>
    [AllowAnonymous]
    public async Task<IActionResult> List(
        string? searchText = null,
        int pageNumber = 1,
        int pageSize = 12,
        int? manufacturerId = null,
        SortOrder sortOrder = SortOrder.Ascending,
        SortBy sortBy = SortBy.Price)
    {
        IQueryable<Book> books = _context
            .Books
            .Include(x => x.Manufacturer)
            .Include(x => x.Types)
            .Include(x => x.Authors);

        var filteredBooks = books
            .FullTextSearchQuery(searchText);

        if (manufacturerId != null)
        {
            filteredBooks = filteredBooks
                .Where(x => x.ManufacturerId == manufacturerId);
        }

        var sortedBooks = sortOrder == SortOrder.Ascending
            ? filteredBooks.OrderBy(b => b.Price)
            : filteredBooks.OrderByDescending(x => x.Price);

        var pagedBooks = await sortedBooks
            .Skip((pageNumber - 1) * pageSize)
            .Take(pageSize)
            .ToListAsync();

        var viewModel = new BookStoreListViewModel(
            searchText,
            pageNumber,
            pageSize,
            await sortedBooks.CountAsync(),
            manufacturerId,
            sortOrder,
            sortBy,
            pagedBooks,
            await _context.Manufacturers.ToListAsync());

        return View(viewModel);
    }

    [AllowAnonymous]
    public IActionResult Privacy()
    {
        return View();
    }

    /// <summary>
    /// Страница книги в каталоге.
    /// </summary>
    [AllowAnonymous]
    public async Task<IActionResult> Book(int bookId)
    {
        var book = _context
            .Books
            .Include(x => x.Manufacturer)
            .Include(x => x.Types)
            .Include(x => x.Authors)
            .Include(x => x.Genres)
            .Include(x => x.Reviews)
            .ThenInclude(x => x.CreatedBy)
            .FirstOrDefault(x => x.Id == bookId);

        ViewBag.BookId = book.Id;

        var viewModel = new BookViewModel
        {
            Book = book,
            Review = new Review()
        };
        
        return View(viewModel);
    }

    [AllowAnonymous]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

MyBookStore.MvcApp/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyBookStore.MvcApp.Models;
using MyBookStore.MvcApp.Models.EF;
using MyBookStore.MvcApp.Models.ViewModels;

namespace MyBookStore.MvcApp.Controllers;

/// <summary>
/// Операции над корзиной.
/// </summary>
[Authorize]
public class CartController : Controller
{
    private readonly BookStoreContext _context;
    private readonly Cart _cart;

    public CartController(BookStoreContext context, Cart cart)
    {
        _context = context;
        _cart = cart;
    }

    /// <summary>
    /// Корзина.
    /// </summary>
    /// <param name="returnUrl">Адрес страницы для возврата.</param>
    [AllowAnonymous]
    public IActionResult Index(string returnUrl)
    {
        return View(new CartIndexViewModel
        {
            Cart = _cart,
            ReturnUrl = returnUrl
        });
    }

    /// <summary>
    /// Добавить в корзину.
    /// </summary>
    /// <param name="returnUrl">Адрес страницы для возврата.</param>
    [AllowAnonymous]
    public IActionResult AddToCart(int bookId, string returnUrl, int quantity = 1)
    {
        var book = _context
            .Books
            .Include(b => b.Manufacturer)
            .Include(x => x.Authors)
            .Include(x => x.Genres)
            .FirstOrDefault(p => p.Id == bookId);

        if (book == null)
        {
            return RedirectToAction("Index", new {returnUrl});
        }

        _cart.AddItem(book, quantity);

        return RedirectToAction("Index", new {returnUrl});
    }

    /// <summary>
    /// Удалить из корзины.
    /// </summary>
    /// <param name="returnUrl">Адрес страницы для возврата.</param>
    [AllowAnonymous]
    public IActionResult RemoveFromCart(int bookId, string returnUrl)
    {
        var book = _context
            .Books
            .FirstOrDefault(p => p.Id == bookId);

        if (book == null)
        {
            return RedirectToAction("Index", new {returnUrl});
        }

        _cart.RemoveLine(book);

        return RedirectToAction("Index", new {returnUrl});
    }
}

MyBookStore.MvcApp/Views/Cart/Partial/_CartLine.cshtml
@using MyBookStore.MvcApp.Infrastructure
@model CartLine

<div class="container mb-5 p-0">
    <div class="card">
        <div class="card-body p-0">
            <div class="row align-items-center">
                <div class="col">
                    <img class="card-img-left" src="@Model?.Book.ImagePath" width="200" height="300"/>
                </div>
                <div class="col-md">
                    <h3 class="fw-bolder">
                        <a asp-controller="BookStore"
                           asp-action="Book"
                           asp-route-bookId="@Model.Book.Id"
                           class="link-dark">
                            @Model?.Book.Title
                        </a>
                    </h3>
                    <p class="small">
                        @String.Join(", ", Model
                            .Book
                            .Authors
                            .Select(x => x.ToString())
                            .ToArray())
                    </p>
                    <dl class="small m-b-none">
                        <dt>Жанры</dt>
                        <dd>
                            @String.Join(", ", Model
                                .Book
                                .Genres
                                .Select(x => x.Name.ToString())
                                .ToArray())
                        </dd>
                    </dl>
                </div>
                <div class="col-sm">
                    <h4>
                        <div class="text-nowrap">
                            @Model.Total.ToString("C")
                        </div>
                    </h4>
                    <div class="d-flex flex-column">
                        <div class="text-nowrap">
                            Цена: @Model.Book.Price.ToString("C")
                        </div>
                        <div class="text-nowrap">
                            Количество: @Model.Quantity
                        </div>
                    </div>
                    <form asp-action="RemoveFromCart" method="post">
                        <input type="hidden" name="bookId" value="@Model.Book.Id"/>
                        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
                        <button type="submit" class="btn btn-outline-danger" placeholder="2">
                            <i class="bi bi-trash3"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>